[phases.setup]
nixPkgs = ["php83", "php83Extensions.mbstring", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.gd", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t frontend/web"