<?php

namespace api\models;

use Yii;
use yii\helpers\Url;
use yii\web\Response;

class Category extends \common\models\Category
{

    public function fields()
    {
        $fields = parent::fields();
        unset($fields['order'], $fields['status']);
        return $fields;

    }

    public function afterFind()
    {
        $this->img = "https://shop.nugaev.uz/" . $this->img;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}